"""another migrate

Revision ID: 563d767bcbd5
Revises: 75a449a95f5f
Create Date: 2022-05-19 03:09:17.754479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563d767bcbd5'
down_revision = '75a449a95f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_content'), 'comments', ['content'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_expenses_description'), 'expenses', ['description'], unique=False)
    op.create_index(op.f('ix_expenses_merchant'), 'expenses', ['merchant'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_merchant'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_description'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_comments_content'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
